[build-system]

requires = ["setuptools",
            "wheel",
            "numpy<2.0,<3; python_version<'3.9'",
            "numpy>=2.0,<3; python_version>='3.9' and python_version<'3.13'",
            "numpy>=2.1,<3; python_version>='3.13'"]

build-backend = 'setuptools.build_meta'
